### PR TITLE
Typescript support

### LINKED ISSUE #43: Support for Typescript
Hi,

I am currently working on a JavaScript library using graphlib. I use Typescript to enhance the development.

What about add a typescript support ?

You can support Typescript by defining a ["definition file"](http://www.typescriptlang.org/Handbook#writing-dts-files) which expose the external library API. It mainly exists for compile time check.

### PR DESCRIPTION
**Pull request by ValentinTrinque**
Should fix #43 .

Finished but not yet tested.

WIP.

### CODE REVIEW

**Comment by cpettitt** [comment]
I don't know a lot about type script definitions, but this looks good. It would be great to have the version generated from package.json, similar to how we're generating bower.json.

**Comment by ValentinTrinque** [comment]
UPDATE:

I, a little bit, gave up on TypeScript dev for my project and so I couldn't tested properly this definition file.

I would advise to merge this, but only under "alpha version" label.

Regards.

**Comment by mserranom** [comment]
Please avoid merging this, it contains errors on return types, incompatibilities with Typescript 1.5+ and lacks generic types for nodes and edges.

I use a version with some quick fixes, if anyone shows interest I'll create a new pull request with a complete d.ts

**Comment by cpettitt** [comment]
I'd be happy to apply a pull request with fixed / improved definitions.

**Comment by ValentinTrinque** [comment]
Then, please, provide your changes because I do not plan to fix this since I am not in TypeScript development.

It has been written with TypeScript 1.4 in mind.

Since you want to create your own PR, I will close this one and delete it.

**Pull request closed without merging**
