### PR TITLE
updated browserify version to 13.0.0 for correct amd support

### PR DESCRIPTION
**Pull request by sprilukin**
@cpettitt i've updated browserify to 13.0.0 and both tests and my local verification with requirejs works perfectly with this PR.

#32, #38

### CODE REVIEW

**Comment by sprilukin** [comment]
@cpettitt i've updated browserify to 13.0.0 and both tests and my local verification with requirejs works perfectly with this PR.

**Comment by sprilukin** [comment]
unfortunately ```graphlib.core.js``` still does not works with requirejs - 
```lodash``` dependency could not be loaded even if it's correctly described in require.config.
Probably some additional magic should be done with browserify config and/or local ```./lodash.js``` stub which is used for loading real lodash.

**Comment by sprilukin** [comment]
I've added karma tests for both full graphlib and graphlib.core in amd environment.

**Comment by cpettitt** [comment]
Merge and release in v2.1.0. Thanks!

**Comment by sprilukin** [comment]
yw! glad i can use original lib instead of fork now :thumbsup:

**Comment by sprilukin** [comment]
It's possible to make graphlib.core in amd env even without shim,
but changes in browserify should be done for this.
Related issue for browserify already exists: https://github.com/substack/node-browserify/issues/1225

in short: browserify in -s mode wraps files in umd wrapper which for amd purpose has something like:

```js
if (typeof define === "function" && define.amd) {
    define([], f) // if replace it with define(['lodash'], f) no shim necessary anymore
  }
```

as you see dependencies array is empty.
I would expect that when browserify is called with --external param 
external library will appears in this dependencies array, moreover i've tested graphlib.core with this change and it works well.

**Pull request closed without merging**
